"""Initial migration

Revision ID: 2ce62974bd3d
Revises: 
Create Date: 2025-11-22 22:30:08.545300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce62974bd3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics_pool',
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_pics_pool_type', 'pics_pool', ['type'], unique=False)
    op.create_table('user_demo',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('utc_offset', sa.Integer(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consent_dt', sa.DateTime(), nullable=True),
    sa.Column('consent_ip', sa.Text(), nullable=True),
    sa.Column('payer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('tg_id > 0', name='tg_id_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('pairs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid_a', sa.BigInteger(), nullable=False),
    sa.Column('uid_b', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('common_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('uid_a < uid_b', name='uid_order_check'),
    sa.ForeignKeyConstraint(['uid_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pairs_common_chat', 'pairs', ['common_chat_id'], unique=False)
    op.create_index('idx_pairs_status_mode', 'pairs', ['status', 'mode'], unique=False)
    op.create_table('daily_state',
    sa.Column('pair_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('morning_initiator', sa.BigInteger(), nullable=True),
    sa.Column('morning_file_id', sa.Text(), nullable=True),
    sa.Column('evening_initiator', sa.BigInteger(), nullable=True),
    sa.Column('evening_file_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_id', 'day')
    )
    op.create_index('idx_daily_state_created_at', 'daily_state', ['created_at'], unique=False)
    op.create_index('idx_daily_state_day', 'daily_state', ['day'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair_id', sa.BigInteger(), nullable=False),
    sa.Column('payer_id', sa.BigInteger(), nullable=False),
    sa.Column('yoo_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yoo_id')
    )
    op.create_index('idx_subscriptions_period', 'subscriptions', ['period_end', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscriptions_period', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_daily_state_day', table_name='daily_state')
    op.drop_index('idx_daily_state_created_at', table_name='daily_state')
    op.drop_table('daily_state')
    op.drop_index('idx_pairs_status_mode', table_name='pairs')
    op.drop_index('idx_pairs_common_chat', table_name='pairs')
    op.drop_table('pairs')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_demo')
    op.drop_index('idx_pics_pool_type', table_name='pics_pool')
    op.drop_table('pics_pool')
    # ### end Alembic commands ###

