"""add_preferred_mode_to_users

Revision ID: 84b63ce9899e
Revises: 2ce62974bd3d
Create Date: 2025-11-22 22:45:13.287852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b63ce9899e'
down_revision: Union[str, None] = '2ce62974bd3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_mode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_mode')
    # ### end Alembic commands ###

